### ISSUE TITLE
Error when running action on my repo

### ISSUE THREAD

**Issue by knice** [katydecorah/wordle-to-yaml-action#15]
I know this is a personal project, so respond to this as your time allows (or not at all is OK too). I'm trying to get this working on [my personal site](https://github.com/knice/knice.github.io)), and I keep getting an error when it runs. I'm not sure what the error means, other than it looks like an array isn't being instantiated before that part of the code runs.

The workflow file (with `wordleFileName` option added):
https://github.com/knice/knice.github.io/blob/master/.github/workflows/wordle.yml

An example action run that failed:
https://github.com/knice/knice.github.io/runs/5074774413?check_suite_focus=true

Screenshot:
![screenshot-2022-02-04-172033](https://user-images.githubusercontent.com/36719/152623214-228c6621-e82a-43ac-9e7b-04be49acda5e.jpg)

**Comment by katydecorah** [comment]
Aha! I think I have an idea what's going on. I think the code is assuming the yaml file already has contents and is failing on an empty file.

I can push a fix sometime this weekend, or, if you'd like to unstick yourself, try to add some yaml to worldle.yaml. (Anything valid yaml will do, you can remove it later.)

**Comment by knice** [comment]
That worked! Thank you for the tip! I added the sample entry from your README file and then removed it after successfully sending my own Wordle result from today. I really appreciate your help. Thank you so much!
