### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'push')

### ISSUE THREAD

**Issue by andeersg** [katydecorah/wordle-to-yaml-action#20]
Hi,

I really love the idea of shortcuts + actions to track this kind of data 👍 I get an error when the action runs, I was wondering if you have encountered it and have any ideas?

I understand if you don't have time for issues here, no problem :) 

The action fails with "Error: Cannot read properties of undefined (reading 'push')".
I have made sure all files are present.

**Comment by andeersg** [comment]
Thank you for the fast reply! I'm using the latest version, so there seem to still be some problems with empty yaml files. I may have had two empty lines in mine.

But the workaround to add a example entry worked :D

**Comment by katydecorah** [comment]
Thanks for letting me know!
